/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PackingItemRequest } from '../../models/packing-item-request';
import { PackingItemView } from '../../models/packing-item-view';

export interface CreatePackingItem$Params {
  tripId: number;
      body: PackingItemRequest
}

export function createPackingItem(http: HttpClient, rootUrl: string, params: CreatePackingItem$Params, context?: HttpContext): Observable<StrictHttpResponse<PackingItemView>> {
  const rb = new RequestBuilder(rootUrl, createPackingItem.PATH, 'post');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PackingItemView>;
    })
  );
}

createPackingItem.PATH = '/api/trips/{tripId}/packing';
