/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripPacking } from '../../models/trip-packing';

export interface ListPacking$Params {
  tripId: number;
}

export function listPacking(http: HttpClient, rootUrl: string, params: ListPacking$Params, context?: HttpContext): Observable<StrictHttpResponse<TripPacking>> {
  const rb = new RequestBuilder(rootUrl, listPacking.PATH, 'get');
  if (params) {
    rb.path('tripId', params.tripId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripPacking>;
    })
  );
}

listPacking.PATH = '/api/trips/{tripId}/packing';
