/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatedResetView } from '../../models/created-reset-view';
import { CreateResetRequest } from '../../models/create-reset-request';

export interface CreateReset$Params {
  userId: number;
      body: CreateResetRequest
}

export function createReset(http: HttpClient, rootUrl: string, params: CreateReset$Params, context?: HttpContext): Observable<StrictHttpResponse<CreatedResetView>> {
  const rb = new RequestBuilder(rootUrl, createReset.PATH, 'post');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreatedResetView>;
    })
  );
}

createReset.PATH = '/api/admin/accounts/{userId}/resets';
