/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PasswordResetView } from '../../models/password-reset-view';

export interface ListResets$Params {
  userId: number;
}

export function listResets(http: HttpClient, rootUrl: string, params: ListResets$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PasswordResetView>>> {
  const rb = new RequestBuilder(rootUrl, listResets.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PasswordResetView>>;
    })
  );
}

listResets.PATH = '/api/admin/accounts/{userId}/resets';
