/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddMemberRequest } from '../../models/add-member-request';
import { TripMemberView } from '../../models/trip-member-view';

export interface AddMember$Params {
  tripId: number;
      body: AddMemberRequest
}

export function addMember(http: HttpClient, rootUrl: string, params: AddMember$Params, context?: HttpContext): Observable<StrictHttpResponse<TripMemberView>> {
  const rb = new RequestBuilder(rootUrl, addMember.PATH, 'post');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripMemberView>;
    })
  );
}

addMember.PATH = '/api/trips/{tripId}/members';
