/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChangeRoleRequest } from '../../models/change-role-request';
import { TripMemberView } from '../../models/trip-member-view';

export interface ChangeMemberRole$Params {
  tripId: number;
  userId: number;
      body: ChangeRoleRequest
}

export function changeMemberRole(http: HttpClient, rootUrl: string, params: ChangeMemberRole$Params, context?: HttpContext): Observable<StrictHttpResponse<TripMemberView>> {
  const rb = new RequestBuilder(rootUrl, changeMemberRole.PATH, 'put');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.path('userId', params.userId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripMemberView>;
    })
  );
}

changeMemberRole.PATH = '/api/trips/{tripId}/members/{userId}/role';
