/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripMemberView } from '../../models/trip-member-view';

export interface ListMembers$Params {
  tripId: number;
}

export function listMembers(http: HttpClient, rootUrl: string, params: ListMembers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TripMemberView>>> {
  const rb = new RequestBuilder(rootUrl, listMembers.PATH, 'get');
  if (params) {
    rb.path('tripId', params.tripId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TripMemberView>>;
    })
  );
}

listMembers.PATH = '/api/trips/{tripId}/members';
