/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripWeather } from '../../models/trip-weather';

export interface GetTripWeather$Params {
  tripId: number;
}

export function getTripWeather(http: HttpClient, rootUrl: string, params: GetTripWeather$Params, context?: HttpContext): Observable<StrictHttpResponse<TripWeather>> {
  const rb = new RequestBuilder(rootUrl, getTripWeather.PATH, 'get');
  if (params) {
    rb.path('tripId', params.tripId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripWeather>;
    })
  );
}

getTripWeather.PATH = '/api/trips/{tripId}/weather';
