/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlaceSuggestion } from '../../models/place-suggestion';

export interface SearchPlaces$Params {
  q: string;
  limit?: number;
}

export function searchPlaces(http: HttpClient, rootUrl: string, params: SearchPlaces$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PlaceSuggestion>>> {
  const rb = new RequestBuilder(rootUrl, searchPlaces.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PlaceSuggestion>>;
    })
  );
}

searchPlaces.PATH = '/api/geo/search';
