/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminUserView {
  createdAt: string;
  disabled: boolean;
  disabledAt?: string;
  displayName: string;
  email: string;
  id: number;
  role: 'USER' | 'ADMIN';
}
