/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePlaceRequest {
  address?: string;
  category?: string;
  dayDate: string;
  latitude?: number;
  longitude?: number;
  name: string;
  notes?: Array<string>;
  osmRef?: string;
  startsAt?: string;
}
