/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PasswordResetView } from '../models/password-reset-view';
export interface CreatedResetView {
  path: string;
  reset: PasswordResetView;
  token: string;
}
