/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TripInviteView } from '../models/trip-invite-view';
export interface CreatedInviteView {
  invite: TripInviteView;
  path: string;
  token: string;
}
