/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTripRequest {
  currency?: string;
  destination?: string;
  endDate: string;
  name: string;
  startDate: string;
}
