/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RouteStopView } from '../models/route-stop-view';
export interface DayRoutePreview {
  attribution: string;
  attributionUrl: string;
  changed: boolean;
  currentSeconds: number;
  dayDate: string;
  profile: string;
  proposedMetres: number;
  proposedSeconds: number;
  stops: Array<RouteStopView>;
}
