/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RouteLegView } from '../models/route-leg-view';
export interface DayRouteLegsView {
  attribution: string;
  attributionUrl: string;
  dayDate: string;
  legs: Array<RouteLegView>;
  profile: string;
}
