/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DayWeatherView {
  date: string;
  summary: string;
  tempMaxC: number;
  tempMinC: number;
  weatherCode: number;
}
