/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExchangeRateView {
  convertedMinor?: number;
  from: string;
  on: string;
  quotedOn: string;
  rate: string;
  to: string;
}
