/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PersonBalance } from '../models/person-balance';
import { SettlementView } from '../models/settlement-view';
export interface ExpenseSummary {
  balances: Array<PersonBalance>;
  settlements: Array<SettlementView>;
  totalMinor: number;
}
