/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExpenseShareView } from '../models/expense-share-view';
export interface ExpenseView {
  amountMinor: number;
  description: string;
  id: number;
  paidByName: string;
  paidByUserId: number;
  shares: Array<ExpenseShareView>;
  spentOn: string;
  splitMode: 'EQUAL' | 'EXACT';
}
