/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExpenseShareInput } from '../models/expense-share-input';
export interface ExpenseRequest {
  amountMinor: number;
  currency?: string;
  description: string;
  fxRate?: string;
  paidByUserId: number;
  shares: Array<ExpenseShareInput>;
  spentOn: string;
  splitMode: 'EQUAL' | 'EXACT';
}
