/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MapConfig } from '../models/map-config';
export interface InstanceConfig {
  map: MapConfig;
  searchEnabled: boolean;
}
