/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MapConfig } from '../models/map-config';
export interface InstanceConfig {
  bookingDocumentImport: boolean;
  bookingImportEnabled: boolean;
  buildRef: string;
  defaultCurrency: string;
  demoSweepMinutes: number;
  map: MapConfig;
  rateAttribution: string;
  rateAttributionUrl: string;
  rateLookupEnabled: boolean;
  searchEnabled: boolean;
  sourceUrl: string;
  version: string;
  weatherEnabled: boolean;
}
