/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvitePreview {
  invitedByName: string;
  joinable: boolean;
  reason: string;
  role: 'OWNER' | 'EDITOR' | 'VIEWER';
  tripId?: number;
  tripName: string;
}
