/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MapConfig {
  attribution: string;
  darkStyleUrl: string;
  enabled: boolean;
  maxZoom: number;
  styleUrl: string;
  tileUrl: string;
}
