/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PackingItemView } from '../models/packing-item-view';
export interface PackingGroup {
  displayName?: string;
  items: Array<PackingItemView>;
  packedCount: number;
  stillAMember: boolean;
  userId?: number;
}
