/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PackingItemView {
  assigneeUserId?: number;
  description: string;
  id: number;
  packed: boolean;
  packedByName?: string;
}
