/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PasswordResetView {
  createdAt: string;
  createdByName: string;
  expiresAt: string;
  id: number;
  status: 'PENDING' | 'USED' | 'REVOKED' | 'EXPIRED';
  usedAt?: string;
}
