/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentRequest {
  amountMinor: number;
  currency?: string;
  fromUserId: number;
  fxRate?: string;
  note?: string;
  paidOn: string;
  toUserId: number;
}
