/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentRequest {
  amountMinor: number;
  fromUserId: number;
  note?: string;
  paidOn: string;
  toUserId: number;
}
