/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PersonBalance {
  displayName: string;
  netMinor: number;
  paidMinor: number;
  shareMinor: number;
  stillAMember: boolean;
  userId: number;
}
