/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PhotoCandidateView {
  author: string;
  licence: string;
  sourceUrl: string;
  thumbUrl: string;
  url: string;
}
