/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlaceView {
  address?: string;
  category?: string;
  dayDate: string;
  enrichable: boolean;
  id: number;
  latitude?: number;
  longitude?: number;
  name: string;
  notes: Array<string>;
  photoAuthor?: string;
  photoLicence?: string;
  photoSourceUrl?: string;
  photoThumbUrl?: string;
  photoUrl?: string;
  position: number;
  startsAt?: string;
}
