/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PhotoCandidateView } from '../models/photo-candidate-view';
export interface PlaceEnrichmentView {
  available: boolean;
  fetchedAt?: string;
  openingHours?: string;
  phone?: string;
  photos: Array<PhotoCandidateView>;
  summary?: string;
  summaryLicence?: string;
  summaryUrl?: string;
  title?: string;
  website?: string;
}
