/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlaceView {
  address?: string;
  dayDate: string;
  id: number;
  latitude?: number;
  longitude?: number;
  name: string;
  notes?: string;
  position: number;
}
