/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlaceSuggestion {
  address: string;
  category?: string;
  latitude: number;
  longitude: number;
  name: string;
  ref: string;
}
