/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReservationView {
  confirmation?: string;
  endZone?: string;
  endsAt?: string;
  endsAtLocal?: string;
  id: number;
  kind: 'FLIGHT' | 'TRAIN' | 'BUS' | 'FERRY' | 'CAR' | 'HOTEL' | 'RESTAURANT' | 'ACTIVITY' | 'OTHER';
  notes?: string;
  startZone: string;
  startsAt: string;
  startsAtLocal: string;
  title: string;
}
