/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReservationDraft {
  confirmation?: string;
  endDate?: string;
  endTime?: string;
  endZone?: string;
  kind: 'FLIGHT' | 'TRAIN' | 'BUS' | 'FERRY' | 'CAR' | 'HOTEL' | 'RESTAURANT' | 'ACTIVITY' | 'OTHER';
  notes?: string;
  phone?: string;
  source: 'EXTRACTOR' | 'CALENDAR';
  startDate?: string;
  startTime?: string;
  startZone?: string;
  title: string;
}
