/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RouteStopView {
  located: boolean;
  locked: boolean;
  name: string;
  pinned: boolean;
  placeId: number;
}
