/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionUser {
  demoAccount: boolean;
  displayName: string;
  email: string;
  id: number;
  role: 'USER' | 'ADMIN';
}
