/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SetPhotoRequest {
  author?: string;
  clearing?: boolean;
  licence?: string;
  sourceUrl?: string;
  thumbUrl?: string;
  url?: string;
}
