/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SettlementView {
  amountMinor: number;
  fromName: string;
  fromUserId: number;
  toName: string;
  toUserId: number;
}
