/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SignInConfig {
  demoEmail: string;
  demoPassword: string;
  registrationEnabled: boolean;
  sourceUrl: string;
}
