/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SupportedCurrencies {
  attribution: string;
  attributionUrl: string;
  currencies: Array<string>;
  lookupEnabled: boolean;
}
