/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReservationView } from '../models/reservation-view';
import { TripSummary } from '../models/trip-summary';
export interface TripReservations {
  reservations: Array<ReservationView>;
  trip: TripSummary;
}
