/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PackingGroup } from '../models/packing-group';
import { TripSummary } from '../models/trip-summary';
export interface TripPacking {
  groups: Array<PackingGroup>;
  packedCount: number;
  totalCount: number;
  trip: TripSummary;
}
