/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TripMemberView {
  displayName: string;
  email: string;
  joinedAt: string;
  role: 'OWNER' | 'EDITOR' | 'VIEWER';
  userId: number;
}
