/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TripSummary {
  dayCount: number;
  destination?: string;
  endDate: string;
  id: number;
  myRole: 'OWNER' | 'EDITOR' | 'VIEWER';
  name: string;
  startDate: string;
}
