/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TripDay } from '../models/trip-day';
import { TripSummary } from '../models/trip-summary';
export interface TripItinerary {
  days: Array<TripDay>;
  trip: TripSummary;
}
