/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PlaceView } from '../models/place-view';
export interface TripDay {
  date: string;
  index: number;
  places: Array<PlaceView>;
}
