/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PlaceView } from '../models/place-view';
export interface TripDay {
  date: string;
  index: number;
  note?: string;
  places: Array<PlaceView>;
  spentMinor?: number;
}
