/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DayWeatherView } from '../models/day-weather-view';
export interface TripWeather {
  attribution: string;
  attributionUrl: string;
  available: boolean;
  days: Array<DayWeatherView>;
}
