/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExpenseSummary } from '../models/expense-summary';
import { ExpenseView } from '../models/expense-view';
import { TripSummary } from '../models/trip-summary';
export interface TripExpenses {
  expenses: Array<ExpenseView>;
  summary: ExpenseSummary;
  trip: TripSummary;
}
