/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TripInviteView {
  acceptedAt?: string;
  acceptedByName?: string;
  createdAt: string;
  createdByName: string;
  expiresAt: string;
  id: number;
  role: 'OWNER' | 'EDITOR' | 'VIEWER';
  status: 'PENDING' | 'ACCEPTED' | 'REVOKED' | 'EXPIRED';
}
