-- What the world says about a place.
--
-- Keyed on `osm_ref` and **shared across every trip and user on the instance**,
-- because that is what the row describes: two people with Fushimi Inari on their
-- itineraries are looking at the same shrine. Keying it per place row instead
-- would spend four upstream services' rate budget to store the same paragraph
-- several times.
--
-- Nothing here is authored on this instance and nothing is authoritative. Every
-- text field arrives from somewhere with terms attached, so the source and the
-- licence are stored beside the content rather than assumed.

CREATE TABLE place_enrichment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The join to `places.osm_ref`, and deliberately not a foreign key: this row
    -- outlives any particular trip's copy of the place and is shared between them.
    osm_ref         VARCHAR(40)  NOT NULL,
    -- Null when OpenStreetMap has no `wikidata` tag, which is most places.
    wikidata_id     VARCHAR(32),
    title           VARCHAR(300),
    summary         VARCHAR(2000),
    -- Where the summary came from and under what terms. CC BY-SA obliges both to
    -- be shown wherever the text is.
    summary_url     VARCHAR(500),
    summary_licence VARCHAR(120),
    -- OpenStreetMap's own `opening_hours` specification, stored verbatim and
    -- never parsed. A raw "Mo-Su 06:00-18:00" beside the date it was last checked
    -- is something a person can judge; an app-computed "Open now" is a claim this
    -- data cannot support, and people plan around hours.
    opening_hours   VARCHAR(500),
    website         VARCHAR(500),
    phone           VARCHAR(80),
    -- Doubles as the TTL and as the "checked on" date shown beside the hours.
    fetched_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_place_enrichment_ref UNIQUE (osm_ref)
);

-- Photo candidates, in the order they are offered.
--
-- `author` and `licence` are NOT NULL because a Commons image is licensed *per
-- image* — CC BY, CC BY-SA, public domain — and the terms for one say nothing
-- about the next. A candidate whose credit could not be read is not stored, and
-- therefore cannot be offered: showing a picture without its attribution is the
-- one failure in this feature that is a licensing problem rather than a bug.
CREATE TABLE place_enrichment_photo (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrichment_id BIGINT       NOT NULL REFERENCES place_enrichment (id) ON DELETE CASCADE,
    url           VARCHAR(500) NOT NULL,
    thumb_url     VARCHAR(500) NOT NULL,
    author        VARCHAR(300) NOT NULL,
    licence       VARCHAR(120) NOT NULL,
    source_url    VARCHAR(500) NOT NULL,
    position      INT          NOT NULL
);

CREATE INDEX ix_place_enrichment_photo ON place_enrichment_photo (enrichment_id, position);
