-- A place holds several notes of its own, and optionally a time of day.
--
-- One `places.notes` column became the limit as soon as anybody wanted to write
-- more than one thought about a place: "come before eight, the approach is yours
-- alone" and "free entry, the covered street sells cakes" are two notes, not one
-- paragraph with a blank line in it.

CREATE TABLE place_note (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT        NOT NULL REFERENCES places (id) ON DELETE CASCADE,
    body     VARCHAR(2000) NOT NULL,
    -- Dense and zero-based, renumbered whenever the list is written. The same
    -- shape as `expense_shares`: notes are replaced as a set, never patched
    -- individually, so there is no half-written state to reconcile.
    position INT           NOT NULL
);

CREATE INDEX ix_place_note_place ON place_note (place_id, position);

-- Existing notes become each place's first block. Done here rather than left to
-- the application: a migration that moves data is the only place the two shapes
-- are both true at once.
INSERT INTO place_note (place_id, body, position)
SELECT id, notes, 0 FROM places WHERE notes IS NOT NULL AND btrim(notes) <> '';

-- And the old column goes. Leaving one that nothing writes is a trap for whoever
-- reads the entity next and finds two plausible homes for the same fact.
ALTER TABLE places DROP COLUMN notes;

-- The time of day, and deliberately a plain TIME rather than the instant-plus-zone
-- that `reservations` carries. That machinery exists because a flight leaves one
-- zone and lands in another; a place's "08:00" is 08:00 where the place is, on a
-- day the trip has already fixed. A TIMESTAMPTZ here would demand a zone nobody
-- has any reason to type.
--
-- It does not affect ordering. A day keeps the manual order that `PlaceService`
-- renumbers on every drag: sorting by time would fight that, and would leave the
-- untimed places with nowhere to sit.
ALTER TABLE places ADD COLUMN starts_at TIME;
