-- The forecast for a day of a trip.
--
-- Cached in a table rather than in memory for the same reason enrichments are:
-- an instance restart should not send everybody's trip page back to Open-Meteo,
-- and the free tier's budget is "less than 10'000 API calls per day" for the
-- whole instance.
--
-- Unlike `place_enrichment`, this is **per trip and per day**, not global. A
-- forecast is about a moment as much as a place, and the day's location comes
-- from that trip's own itinerary — two trips passing through Kyoto on different
-- days want different rows, and on the same day they still ask about different
-- coordinates.
CREATE TABLE day_weather (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id      BIGINT           NOT NULL REFERENCES trips (id) ON DELETE CASCADE,
    -- A plain date, as everywhere a day is addressed in this schema: days are
    -- derived from the trip's range and have no rows of their own.
    day_date     DATE             NOT NULL,
    -- The point this forecast was fetched for, kept so that moving the day's
    -- first place invalidates the row. Without it the card would go on showing
    -- Osaka's weather for a day that is now spent in Kanazawa.
    latitude     DOUBLE PRECISION NOT NULL,
    longitude    DOUBLE PRECISION NOT NULL,
    temp_max_c   DOUBLE PRECISION NOT NULL,
    temp_min_c   DOUBLE PRECISION NOT NULL,
    -- A WMO code. Stored raw rather than as words, because the words are this
    -- application's presentation of it and the number is what the upstream said.
    weather_code INTEGER          NOT NULL,
    -- Both the TTL and, if it ever needs showing, the honest answer to "as of
    -- when". A forecast changes through the day, so this expires in hours where
    -- an enrichment expires in weeks.
    fetched_at   TIMESTAMPTZ      NOT NULL DEFAULT now(),
    CONSTRAINT uq_day_weather UNIQUE (trip_id, day_date)
);
