-- An invitation to a trip, for somebody who has no account yet.
--
-- This is the last piece of sharing. `trip_members` can only add a person who
-- already has an account here, because it works by email address and nothing in
-- this instance sends mail. An invite link needs no mail: the owner creates one
-- and delivers it themselves, over whatever they already use to talk to the
-- person. Delivery was never wander's problem — that is why the feature was
-- unblocked all along.
--
-- The token is stored **hashed**, never in the clear. Everything else in this
-- schema is data its owner may read back; a live invitation is a credential, and
-- the one thing that separates it from a password is that nobody has to remember
-- it. The database is dumped nightly and those dumps are copied off the machine,
-- so a token stored in the clear turns any leaked backup into a set of working
-- keys to other people's trips. Hashed, a leaked dump is inert.
--
-- SHA-256 rather than bcrypt, deliberately, and it is the opposite reasoning to
-- `users.password_hash`. Bcrypt is slow on purpose because a password is short
-- and guessable, and guessing must be made expensive. This token is 256 bits
-- from a CSPRNG: there is nothing to guess, and a deliberately slow hash would
-- buy nothing while making the lookup un-indexable — the server must find a row
-- *by* the presented token, which a per-row salt makes impossible without
-- scanning every invitation on the instance.
CREATE TABLE trip_invites (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id             BIGINT      NOT NULL REFERENCES trips (id) ON DELETE CASCADE,
    -- Hex SHA-256 of the token. Unique, so a lookup is one indexed read, and so
    -- the impossible collision is a constraint violation rather than the wrong
    -- trip being joined.
    --
    -- VARCHAR, not CHAR(64), even though the digest is always exactly 64
    -- characters. Postgres implements CHAR(n) as `bpchar` with blank padding and
    -- recommends against it, and Hibernate's `ddl-auto: validate` rejects it
    -- outright against a String field — which is how this was caught, before the
    -- migration had been applied anywhere.
    token_hash          VARCHAR(64) NOT NULL,
    -- EDITOR or VIEWER. Never OWNER: a trip has exactly one owner and the only
    -- way it moves is a transfer, so a link that granted it would be a second
    -- path to a state TripMemberService is built to make unreachable.
    role                VARCHAR(16) NOT NULL,
    created_by_user_id  BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Not nullable: a link that never expires is a key left under a doormat for
    -- years, and the person who pasted it into a group chat has long forgotten.
    expires_at          TIMESTAMPTZ NOT NULL,
    -- Single use. Set together with accepted_by_user_id when somebody joins, so
    -- a link forwarded on cannot quietly add a second stranger.
    accepted_at         TIMESTAMPTZ,
    accepted_by_user_id BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    -- Revoked rather than deleted, so the owner's list can say what became of a
    -- link they remember sending. The row is small and the history is the answer
    -- to "did that ever get used".
    revoked_at          TIMESTAMPTZ,
    CONSTRAINT uq_trip_invites_token UNIQUE (token_hash)
);

-- The owner's list of outstanding invitations for one trip, newest first.
CREATE INDEX idx_trip_invites_trip ON trip_invites (trip_id, created_at DESC);
