-- The admin surface: an account that can be taken out of service, and a way to
-- put a password back without sending mail.
--
-- `users.role` has carried ADMIN since V1 and granted nothing: the first-boot
-- account was labelled an administrator and had exactly the authority of anybody
-- else. These two changes are what the label finally means.

-- Disabled rather than deleted, and a timestamp rather than a boolean.
--
-- Deleting an account is not available and should not be: `expenses` and
-- `packing_items` reference their user, a departed member's shares are history
-- the trip still needs (see PersonBalance.stillAMember), and a cascade here
-- would silently forgive debts on somebody else's trip. Disabling stops the
-- account being used without rewriting what it did.
--
-- The timestamp is worth more than a flag for the same reason `revoked_at` is on
-- trip_invites: "when did this happen" is the first question asked about an
-- account that has been shut off, and the row is no bigger for answering it.
ALTER TABLE users ADD COLUMN disabled_at TIMESTAMPTZ;

-- A one-shot permission to set one account's password, without knowing the old
-- one.
--
-- This exists because nothing in wander sends mail, and the usual answer to a
-- forgotten password does. Until now the only recovery was the operator editing
-- `users.password_hash` by hand, which README stated plainly as the limit on how
-- wide an instance could go. An admin-minted link needs no mail for the same
-- reason a trip invitation does not: the operator already has a way to talk to
-- the person, and delivery was never this application's problem.
--
-- The token is stored **hashed**, exactly as `trip_invites.token_hash` is, and
-- for a sharper version of the same reason: this one sets a password. A nightly
-- dump leaves this machine, and a token at rest in one would be a working key to
-- an account rather than to a trip.
--
-- SHA-256 rather than bcrypt — again the opposite reasoning to
-- `users.password_hash`. The token is 256 bits from a CSPRNG, so there is
-- nothing to slow a guesser down about, and a per-row salt would turn the
-- lookup-by-token into a scan of every reset ever minted.
CREATE TABLE password_resets (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- ON DELETE CASCADE is a formality: accounts are disabled, not deleted. It
    -- is here so a hand-run DELETE in psql cannot leave a live reset link
    -- pointing at nothing.
    user_id            BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- VARCHAR(64), not CHAR(64): Postgres blank-pads CHAR and Hibernate's
    -- `ddl-auto: validate` rejects it against a String field. See V15, where
    -- that was caught before the migration had been applied anywhere.
    token_hash         VARCHAR(64) NOT NULL,
    created_by_user_id BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Not nullable, and shorter-lived than an invitation in practice: a reset
    -- link is handed over in a conversation that is happening now.
    expires_at         TIMESTAMPTZ NOT NULL,
    -- Single use. Set when the password is actually changed, so a link forwarded
    -- or shoulder-surfed cannot be replayed to take the account back.
    used_at            TIMESTAMPTZ,
    -- Revoked rather than deleted, so the admin's list can say what became of a
    -- link they remember minting — the answer to "did they ever use that".
    revoked_at         TIMESTAMPTZ,
    CONSTRAINT uq_password_resets_token UNIQUE (token_hash)
);

-- The admin's list for one account, newest first.
CREATE INDEX idx_password_resets_user ON password_resets (user_id, created_at DESC);
