-- Baseline schema.
--
-- Multi-tenant from the first migration on purpose: `trip_members` exists even
-- though only its OWNER row is written today. Adding a join table later would
-- mean rewriting every trip query; adding rows to one that already exists is
-- just a feature.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(320)  NOT NULL,
    display_name  VARCHAR(80)   NOT NULL,
    password_hash VARCHAR(200)  NOT NULL,
    role          VARCHAR(16)   NOT NULL,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- Case-insensitive uniqueness: Alice@ and alice@ are one account, and the index
-- is what enforces it rather than a check the application might skip.
CREATE UNIQUE INDEX ux_users_email_lower ON users (LOWER(email));

CREATE TABLE trips (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    destination VARCHAR(120),
    start_date  DATE         NOT NULL,
    end_date    DATE         NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_trips_dates CHECK (end_date >= start_date)
);

CREATE TABLE trip_members (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id   BIGINT      NOT NULL REFERENCES trips (id) ON DELETE CASCADE,
    user_id   BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role      VARCHAR(16) NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_trip_members UNIQUE (trip_id, user_id)
);

-- The access check (trip_id, user_id) runs on every trip-scoped request, and
-- listing a user's trips drives the second one.
CREATE INDEX ix_trip_members_user ON trip_members (user_id);
