-- Places: the itinerary itself. A place belongs to a trip and sits on one of
-- that trip's days.
--
-- `day_date` is a plain date rather than a foreign key, because days are derived
-- from the trip's date range and never stored — there is no days table to point
-- at. The range check that a place falls inside its trip lives in the service:
-- it spans two tables, so a column CHECK cannot express it.

CREATE TABLE places (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id    BIGINT       NOT NULL REFERENCES trips (id) ON DELETE CASCADE,
    day_date   DATE         NOT NULL,
    -- Not named `position`: that is a reserved word in Postgres and would need
    -- quoting at every use site.
    sort_order INT          NOT NULL,
    name       VARCHAR(160) NOT NULL,
    notes      VARCHAR(2000),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Every read is "the places of this trip, in order", which this index serves
-- whole. Deliberately not UNIQUE on (trip_id, day_date, sort_order): reordering
-- renumbers a whole day inside one transaction and would trip a non-deferrable
-- unique constraint halfway through.
CREATE INDEX ix_places_trip_day ON places (trip_id, day_date, sort_order);
