-- A note on one day of a trip: what the day is for, where to eat, the train
-- that has to be caught.
--
-- Like `places.day_date`, the day is a plain date rather than a foreign key —
-- days are derived from the trip's range and have no rows to point at. One note
-- per day, so (trip_id, day_date) is unique; a list of notes per day would be
-- a second thing to order, and the places below it already carry per-place
-- notes.

CREATE TABLE day_notes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id    BIGINT        NOT NULL REFERENCES trips (id) ON DELETE CASCADE,
    day_date   DATE          NOT NULL,
    -- NOT NULL: "this day has no note" is the absence of a row, not a row
    -- holding nothing. Clearing a note deletes it, so there is one
    -- representation of empty rather than two.
    note       VARCHAR(4000) NOT NULL,
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_day_notes_trip_day UNIQUE (trip_id, day_date)
);
