-- What the trip cost, and who owes whom.
--
-- Money is stored as integer minor units — 1234 is 12.34 — and never as a
-- decimal or a float. Every split resolves to whole minor units at write time,
-- so a balance is integer addition and cannot drift by a rounding step.
--
-- One currency per trip, on `trips`, because balances that mix currencies need a
-- rate and a date and stop being arithmetic. Backfilled to EUR: the only rows
-- that exist are on the author's dev instance.

-- VARCHAR(3), not CHAR(3): Postgres implements CHAR as `bpchar`, which
-- space-pads on the way in and which Hibernate's `ddl-auto: validate` rejects
-- outright against a String field. The padding is the worse half — 'EUR ' and
-- 'EUR' comparing unequal is a bug nobody would find quickly.
ALTER TABLE trips ADD COLUMN currency VARCHAR(3) NOT NULL DEFAULT 'EUR';

CREATE TABLE expenses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id         BIGINT       NOT NULL REFERENCES trips (id) ON DELETE CASCADE,
    description     VARCHAR(160) NOT NULL,
    -- BIGINT rather than INTEGER: a JPY trip has no minor unit at all, so a
    -- fortnight in Japan runs into seven figures before anything unusual happens.
    amount_minor    BIGINT       NOT NULL CHECK (amount_minor > 0),
    -- Deliberately not constrained to the trip's date range, unlike places and
    -- day notes: flights and deposits are paid months before anybody travels,
    -- and refusing those dates would only teach people to enter false ones.
    spent_on        DATE         NOT NULL,
    -- No ON DELETE CASCADE, unlike trip_members.user_id. Deleting a person must
    -- not quietly delete money; with no account-deletion path today this is a
    -- guard rather than a behaviour.
    paid_by_user_id BIGINT       NOT NULL REFERENCES users (id),
    -- Stored so an edit reopens in the mode it was saved in. Without it, editing
    -- an equal split shows the resolved amounts and saving again silently turns
    -- it into an exact one.
    split_mode      VARCHAR(8)   NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- The expenses page reads one trip, newest first.
CREATE INDEX ix_expenses_trip ON expenses (trip_id, spent_on DESC);

-- One row per participant, holding the amount that participant owes for this
-- expense. Equal and exact splits both land here identically: the split is a way
-- of *arriving* at these numbers, not a second way of storing them.
CREATE TABLE expense_shares (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id   BIGINT NOT NULL REFERENCES expenses (id) ON DELETE CASCADE,
    user_id      BIGINT NOT NULL REFERENCES users (id),
    -- Zero is allowed: an exact split may legitimately give somebody nothing.
    amount_minor BIGINT NOT NULL CHECK (amount_minor >= 0),
    CONSTRAINT uq_expense_shares UNIQUE (expense_id, user_id)
);
