-- What to bring, and who is bringing it.
--
-- One list per trip rather than a list per person plus a shared one. The
-- difference is `assignee_user_id`: null means everyone's — the tent, the
-- first-aid kit — and anything else is one person's. Reassigning an item is then
-- a field change rather than a move between two kinds of list, and a new member
-- needs nothing created for them.
--
-- No sort_order, on purpose. A packing list is grouped, not ranked: within a
-- person's section, creation order is as good an order as any, and a rank would
-- drag in the renumbering that `PlaceService` needs for something genuinely
-- ordered. Adding drag ordering later is a column and a migration, not a design
-- to undo.

CREATE TABLE packing_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id           BIGINT       NOT NULL REFERENCES trips (id) ON DELETE CASCADE,
    description       VARCHAR(160) NOT NULL,
    -- No ON DELETE CASCADE, matching `expenses`: somebody leaving a trip must not
    -- silently rewrite what it says they were bringing.
    assignee_user_id  BIGINT       REFERENCES users (id),
    packed            BOOLEAN      NOT NULL DEFAULT false,
    -- Which is the answer to "so who has the tent?".
    packed_by_user_id BIGINT       REFERENCES users (id),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- The only read is "this trip's items, in the order they were added".
CREATE INDEX ix_packing_items_trip ON packing_items (trip_id, id);
