-- Bookings: flights, trains, hotels, tables.
--
-- The first thing in this project with a *time* rather than a date, and the only
-- one that has to survive crossing a timezone. Both halves are stored:
--
--   starts_at   TIMESTAMPTZ — the instant, so ordering and "which is first" are
--               answerable without knowing anybody's zone
--   start_zone  the IANA zone it was booked in, because an instant alone cannot
--               be shown as "09:15" again — Postgres stores TIMESTAMPTZ as UTC
--               and throws the original zone away
--
-- A flight has two zones: it leaves Heathrow and lands in Kansai. So the end
-- carries its own, defaulting to the start's when it is the same place.

CREATE TABLE reservations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id      BIGINT       NOT NULL REFERENCES trips (id) ON DELETE CASCADE,
    kind         VARCHAR(16)  NOT NULL,
    title        VARCHAR(160) NOT NULL,
    -- The booking reference. Nullable: a dinner table often has none.
    confirmation VARCHAR(80),
    notes        VARCHAR(2000),
    starts_at    TIMESTAMPTZ  NOT NULL,
    start_zone   VARCHAR(64)  NOT NULL,
    -- Both nullable together: a restaurant booking has no end worth recording.
    ends_at      TIMESTAMPTZ,
    end_zone     VARCHAR(64),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_reservations_order CHECK (ends_at IS NULL OR ends_at >= starts_at),
    -- An end time without the zone to read it in would be undisplayable.
    CONSTRAINT ck_reservations_end_zone CHECK ((ends_at IS NULL) = (end_zone IS NULL))
);

-- The page is "this trip's bookings, soonest first", and the instant is what
-- makes that a total order no matter which zones are involved.
CREATE INDEX ix_reservations_trip ON reservations (trip_id, starts_at);
