/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReservationRequest } from '../../models/reservation-request';
import { ReservationView } from '../../models/reservation-view';

export interface UpdateReservation$Params {
  tripId: number;
  reservationId: number;
      body: ReservationRequest
}

export function updateReservation(http: HttpClient, rootUrl: string, params: UpdateReservation$Params, context?: HttpContext): Observable<StrictHttpResponse<ReservationView>> {
  const rb = new RequestBuilder(rootUrl, updateReservation.PATH, 'put');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.path('reservationId', params.reservationId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReservationView>;
    })
  );
}

updateReservation.PATH = '/api/trips/{tripId}/reservations/{reservationId}';
