/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DayNoteRequest } from '../../models/day-note-request';
import { DayNoteView } from '../../models/day-note-view';

export interface PutDayNote$Params {
  tripId: number;
  date: string;
      body: DayNoteRequest
}

export function putDayNote(http: HttpClient, rootUrl: string, params: PutDayNote$Params, context?: HttpContext): Observable<StrictHttpResponse<DayNoteView>> {
  const rb = new RequestBuilder(rootUrl, putDayNote.PATH, 'put');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.path('date', params.date, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DayNoteView>;
    })
  );
}

putDayNote.PATH = '/api/trips/{tripId}/days/{date}/note';
