/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AcceptedInviteView } from '../../models/accepted-invite-view';

export interface AcceptInvite$Params {
  token: string;
}

export function acceptInvite(http: HttpClient, rootUrl: string, params: AcceptInvite$Params, context?: HttpContext): Observable<StrictHttpResponse<AcceptedInviteView>> {
  const rb = new RequestBuilder(rootUrl, acceptInvite.PATH, 'post');
  if (params) {
    rb.path('token', params.token, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AcceptedInviteView>;
    })
  );
}

acceptInvite.PATH = '/api/invites/{token}/accept';
