/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatedInviteView } from '../../models/created-invite-view';
import { CreateInviteRequest } from '../../models/create-invite-request';

export interface CreateInvite$Params {
  tripId: number;
      body: CreateInviteRequest
}

export function createInvite(http: HttpClient, rootUrl: string, params: CreateInvite$Params, context?: HttpContext): Observable<StrictHttpResponse<CreatedInviteView>> {
  const rb = new RequestBuilder(rootUrl, createInvite.PATH, 'post');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreatedInviteView>;
    })
  );
}

createInvite.PATH = '/api/trips/{tripId}/invites';
