/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripInviteView } from '../../models/trip-invite-view';

export interface ListInvites$Params {
  tripId: number;
}

export function listInvites(http: HttpClient, rootUrl: string, params: ListInvites$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TripInviteView>>> {
  const rb = new RequestBuilder(rootUrl, listInvites.PATH, 'get');
  if (params) {
    rb.path('tripId', params.tripId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TripInviteView>>;
    })
  );
}

listInvites.PATH = '/api/trips/{tripId}/invites';
