/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvitePreview } from '../../models/invite-preview';

export interface PreviewInvite$Params {
  token: string;
}

export function previewInvite(http: HttpClient, rootUrl: string, params: PreviewInvite$Params, context?: HttpContext): Observable<StrictHttpResponse<InvitePreview>> {
  const rb = new RequestBuilder(rootUrl, previewInvite.PATH, 'get');
  if (params) {
    rb.path('token', params.token, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvitePreview>;
    })
  );
}

previewInvite.PATH = '/api/invites/{token}';
