/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InstanceConfig } from '../../models/instance-config';

export interface GetInstanceConfig$Params {
}

export function getInstanceConfig(http: HttpClient, rootUrl: string, params?: GetInstanceConfig$Params, context?: HttpContext): Observable<StrictHttpResponse<InstanceConfig>> {
  const rb = new RequestBuilder(rootUrl, getInstanceConfig.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InstanceConfig>;
    })
  );
}

getInstanceConfig.PATH = '/api/config';
