/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SignInConfig } from '../../models/sign-in-config';

export interface GetSignInConfig$Params {
}

export function getSignInConfig(http: HttpClient, rootUrl: string, params?: GetSignInConfig$Params, context?: HttpContext): Observable<StrictHttpResponse<SignInConfig>> {
  const rb = new RequestBuilder(rootUrl, getSignInConfig.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SignInConfig>;
    })
  );
}

getSignInConfig.PATH = '/api/config/sign-in';
