/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExpenseRequest } from '../../models/expense-request';
import { ExpenseView } from '../../models/expense-view';

export interface CreateExpense$Params {
  tripId: number;
      body: ExpenseRequest
}

export function createExpense(http: HttpClient, rootUrl: string, params: CreateExpense$Params, context?: HttpContext): Observable<StrictHttpResponse<ExpenseView>> {
  const rb = new RequestBuilder(rootUrl, createExpense.PATH, 'post');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExpenseView>;
    })
  );
}

createExpense.PATH = '/api/trips/{tripId}/expenses';
