/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripSummary } from '../../models/trip-summary';
import { UpdateTripRequest } from '../../models/update-trip-request';

export interface UpdateTrip$Params {
  tripId: number;
      body: UpdateTripRequest
}

export function updateTrip(http: HttpClient, rootUrl: string, params: UpdateTrip$Params, context?: HttpContext): Observable<StrictHttpResponse<TripSummary>> {
  const rb = new RequestBuilder(rootUrl, updateTrip.PATH, 'put');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripSummary>;
    })
  );
}

updateTrip.PATH = '/api/trips/{tripId}';
