/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DayRouteLegsView } from '../../models/day-route-legs-view';

export interface EstimateDayRouteLegs$Params {
  tripId: number;
  date: string;
  profile?: 'DRIVING' | 'WALKING' | 'CYCLING';
}

export function estimateDayRouteLegs(http: HttpClient, rootUrl: string, params: EstimateDayRouteLegs$Params, context?: HttpContext): Observable<StrictHttpResponse<DayRouteLegsView>> {
  const rb = new RequestBuilder(rootUrl, estimateDayRouteLegs.PATH, 'post');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.path('date', params.date, {});
    rb.query('profile', params.profile, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DayRouteLegsView>;
    })
  );
}

estimateDayRouteLegs.PATH = '/api/trips/{tripId}/days/{date}/route/legs';
