/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResetPreview } from '../../models/reset-preview';

export interface PreviewReset$Params {
  token: string;
}

export function previewReset(http: HttpClient, rootUrl: string, params: PreviewReset$Params, context?: HttpContext): Observable<StrictHttpResponse<ResetPreview>> {
  const rb = new RequestBuilder(rootUrl, previewReset.PATH, 'get');
  if (params) {
    rb.path('token', params.token, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ResetPreview>;
    })
  );
}

previewReset.PATH = '/api/auth/reset/{token}';
