/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingImportResult } from '../../models/booking-import-result';

export interface ImportReservations$Params {
  tripId: number;
      body?: {
'file': Blob;
}
}

export function importReservations(http: HttpClient, rootUrl: string, params: ImportReservations$Params, context?: HttpContext): Observable<StrictHttpResponse<BookingImportResult>> {
  const rb = new RequestBuilder(rootUrl, importReservations.PATH, 'post');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookingImportResult>;
    })
  );
}

importReservations.PATH = '/api/trips/{tripId}/reservations/import';
