/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlaceView } from '../../models/place-view';
import { ReorderDayRequest } from '../../models/reorder-day-request';

export interface ReorderDay$Params {
  tripId: number;
  date: string;
      body: ReorderDayRequest
}

export function reorderDay(http: HttpClient, rootUrl: string, params: ReorderDay$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PlaceView>>> {
  const rb = new RequestBuilder(rootUrl, reorderDay.PATH, 'post');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.path('date', params.date, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PlaceView>>;
    })
  );
}

reorderDay.PATH = '/api/trips/{tripId}/days/{date}/order';
