/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LockPlaceRequest } from '../../models/lock-place-request';
import { PlaceView } from '../../models/place-view';

export interface SetPlaceLocked$Params {
  tripId: number;
  placeId: number;
      body: LockPlaceRequest
}

export function setPlaceLocked(http: HttpClient, rootUrl: string, params: SetPlaceLocked$Params, context?: HttpContext): Observable<StrictHttpResponse<PlaceView>> {
  const rb = new RequestBuilder(rootUrl, setPlaceLocked.PATH, 'put');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.path('placeId', params.placeId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlaceView>;
    })
  );
}

setPlaceLocked.PATH = '/api/trips/{tripId}/places/{placeId}/locked';
