/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExchangeRateView } from '../../models/exchange-rate-view';

export interface GetExchangeRate$Params {
  from: string;
  to: string;
  on: string;
  amountMinor?: number;
}

export function getExchangeRate(http: HttpClient, rootUrl: string, params: GetExchangeRate$Params, context?: HttpContext): Observable<StrictHttpResponse<ExchangeRateView>> {
  const rb = new RequestBuilder(rootUrl, getExchangeRate.PATH, 'get');
  if (params) {
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
    rb.query('on', params.on, {});
    rb.query('amountMinor', params.amountMinor, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExchangeRateView>;
    })
  );
}

getExchangeRate.PATH = '/api/fx/rate';
