/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SupportedCurrencies } from '../../models/supported-currencies';

export interface ListCurrencies$Params {
}

export function listCurrencies(http: HttpClient, rootUrl: string, params?: ListCurrencies$Params, context?: HttpContext): Observable<StrictHttpResponse<SupportedCurrencies>> {
  const rb = new RequestBuilder(rootUrl, listCurrencies.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SupportedCurrencies>;
    })
  );
}

listCurrencies.PATH = '/api/fx/currencies';
