/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlaceEnrichmentView } from '../../models/place-enrichment-view';

export interface GetPlaceEnrichment$Params {
  tripId: number;
  placeId: number;
}

export function getPlaceEnrichment(http: HttpClient, rootUrl: string, params: GetPlaceEnrichment$Params, context?: HttpContext): Observable<StrictHttpResponse<PlaceEnrichmentView>> {
  const rb = new RequestBuilder(rootUrl, getPlaceEnrichment.PATH, 'get');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.path('placeId', params.placeId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlaceEnrichmentView>;
    })
  );
}

getPlaceEnrichment.PATH = '/api/trips/{tripId}/places/{placeId}/enrichment';
